const productsNew = [
    {
        id: 1,
        name: "حوله لبوبو صورتی",
        source: "/images/Card-img/labubu-pink.jpg",
        type: "حوله تنپوش کودک",
        details: [
            { size: "60", price: 1150000, number: 0 },
            { size: "70", price: 1300000, number: 0 },
            { size: "80", price: 1500000, number: 1 },
            { size: "90", price: 1600000, number: 1 },
            { size: "100", price: 1880000, number: 1 },
        ],
        date: 1,
        sale: 4,
        off: 0,
        color: "#F06292",
    },
    {
        id: 2,
        name: "حوله لبوبو بنفش",
        source: "/images/Card-img/labubu-perple.jpg",
        type: "حوله تنپوش کودک",
        details: [
            { size: "60", price: 1150000, number: 0 },
            { size: "70", price: 1300000, number: 1 },
            { size: "80", price: 1500000, number: 1 },
            { size: "90", price: 1600000, number: 0 },
            { size: "100", price: 1880000, number: 1 },
        ],
        date: 1,
        sale: 4,
        off: 0,
        color: "#BA68C8",
    },
    {
        id: 3,
        name: "حوله باب اسفنجی",
        source: "/images/Card-img/bob-abi.jpg",
        type: "حوله تنپوش کودک",
        details: [
            { size: "60", price: 1150000, number: 1 },
            { size: "70", price: 1300000, number: 1 },
            { size: "80", price: 1500000, number: 1 },
            { size: "90", price: 1600000, number: 1 },
            { size: "100", price: 1880000, number: 1 },
        ],
        date: 1,
        sale: 4,
        off: 0,
        color: "#4DD0E1",
    },
    {
        id: 4,
        name: "حوله ورساچه سفید ",
        source: "/images/Card-img/versach-sefid.jpg",
        type: "حوله تنپوش زنانه",
        details: [
            { size: "S", price: 2300000, number: 0 },
            { size: "M", price: 2600000, number: 1 },
            { size: "L", price: 2890000, number: 1 },
            { size: "XL", price: 3150000, number: 1 },
            { size: "XXL", price: 33800000, number: 0 },
        ],
        date: 1,
        sale: 4,
        off: 0,
        color: "#ffffffff",
    },
    {
        id: 5,
        name: "حوله ورساچه مشکی",
        source: "/images/Card-img/versach-meshki.jpg",
        type: "حوله تنپوش مردانه",
        details: [
            { size: "S", price: 2300000, number: 1 },
            { size: "M", price: 2600000, number: 1 },
            { size: "L", price: 2890000, number: 1 },
            { size: "XL", price: 3150000, number: 1 },
            { size: "XXL", price: 33800000, number: 0 },
        ],
        date: 1,
        sale: 4,
        off: 0,
        color: "#000000",
    },

    {
        id: 6,
        name: "حوله دستی پونی",
        source: "/images/Card-img/pony-30.jpg",
        type: "حوله دستی",
        details: [{ size: "30x30", price: 110000, number: 33 }],
        date: 1,
        sale: 4,
        off: 0,
        color: "#F06292",
    },
    {
        id: 7,
        name: "حوله استخری مردعنکبوتی",
        source: "/images/Card-img/spiderman-gym.jpg",
        type: "حوله استخری",
        details: [{ size: "75x135", price: 880000, number: 2 }],
        date: 1,
        sale: 4,
        off: 0,
        color: "#1976D2",
    },
    {
        id: 8,
        name: "حوله لیلیوم صورتی",
        source: "/images/Card-img/lilium-sorati.jpg",
        type: "حوله تنپوش زنانه",
        details: [
            { size: "S", price: 2300000, number: 1 },
            { size: "M", price: 2600000, number: 1 },
            { size: "L", price: 2890000, number: 1 },
            { size: "XL", price: 3150000, number: 0 },
            { size: "XXL", price: 33800000, number: 0 },
        ],
        date: 1,
        sale: 4,
        off: 0,
        color: "#F06292",
    },
    {
        id: 9,
        name: "حوله لیلیوم شیری",
        source: "/images/Card-img/lilium-shiri.jpg",
        type: "حوله تنپوش زنانه",
        details: [
            { size: "S", price: 2300000, number: 1 },
            { size: "M", price: 2600000, number: 1 },
            { size: "L", price: 2890000, number: 1 },
            { size: "XL", price: 3150000, number: 0 },
            { size: "XXL", price: 33800000, number: 0 },
        ],
        date: 1,
        sale: 4,
        off: 0,
        color: "#ffffffff",
    },
    {
        id: 10,
        name: "حوله کیتی",
        source: "/images/Card-img/kiti-sorati.jpg",
        type: "حوله تنپوش کودک",
        details: [
            { size: "60", price: 1150000, number: 1 },
            { size: "70", price: 1300000, number: 1 },
            { size: "80", price: 1500000, number: 1 },
            { size: "90", price: 1600000, number: 1 },
            { size: "100", price: 1880000, number: 1 },
        ],
        date: 1,
        sale: 4,
        off: 0,
        color: "#F06292",
    },
    {
        id: 11,
        name: "حوله کرومی صورتی",
        source: "/images/Card-img/kuromi-sorati.jpg",
        type: "حوله تنپوش کودک",
        details: [
            { size: "60", price: 1150000, number: 0 },
            { size: "70", price: 1300000, number: 1 },
            { size: "80", price: 1500000, number: 1 },
            { size: "90", price: 1600000, number: 1 },
            { size: "100", price: 1880000, number: 1 },
        ],
        date: 1,
        sale: 4,
        off: 0,
        color: "#F06292",
    },
    {
        id: 12,
        name: "حوله کرومی بنفش",
        source: "/images/Card-img/kuromi-banafsh.jpg",
        type: "حوله تنپوش کودک",
        details: [
            { size: "60", price: 1150000, number: 0 },
            { size: "70", price: 1300000, number: 1 },
            { size: "80", price: 1500000, number: 1 },
            { size: "90", price: 1600000, number: 1 },
            { size: "100", price: 1880000, number: 1 },
        ],
        date: 1,
        sale: 4,
        off: 0,
        color: "#BA68C8",
    },
    {
        id: 13,
        name: "حوله حمامی لویی ویتون",
        source: "/images/Card-img/viton-toosi-bath.jpg",
        type: "حوله حمامی",
        details: [{ size: "90x150", price: 1250000, number: 5 }],
        date: 2,
        sale: 14,
        off: 0,
        color: "#90A4AE",
    },

    {
        id: 14,
        name: "حوله پارادایس صورتی",
        source: "/images/BestSallers/paradais-pink.jpg",
        type: "حوله تنپوش زنانه",
        details: [
            { size: "S", price: 2300000, number: 1 },
            { size: "M", price: 2600000, number: 1 },
            { size: "L", price: 2890000, number: 1 },
            { size: "XL", price: 3150000, number: 0 },
            { size: "XXL", price: 33800000, number: 0 },
        ],
        date: 2,
        sale: 14,
        off: 0.1,
        color: "#F06292",
    },
    {
        id: 15,
        name: "حوله پانچو پونی",
        source: "/images/BestSallers/pony-panchi.jpg",
        type: "حوله استخری",
        details: [{ size: "70", price: 1300000, number: 1 }],
        date: 2,
        sale: 14,
        off: 0,
        color: "#F06292",
    },
    {
        id: 16,
        name: "حوله سورن لیمویی",
        source: "/images/BestSallers/soren-limo.jpg",
        type: "حوله تنپوش زنانه",
        details: [
            { size: "S", price: 2300000, number: 0 },
            { size: "M", price: 2600000, number: 1 },
            { size: "L", price: 2890000, number: 1 },
            { size: "XL", price: 3150000, number: 1 },
            { size: "XXL", price: 33800000, number: 0 },
        ],
        date: 2,
        sale: 14,
        off: 0,
        color: "#FFD54F",
    },
    {
        id: 17,
        name: "حوله آفتاب قهوه ای",
        source: "/images/BestSallers/aftab-kerem.jpg",
        type: "حوله استخری",
        details: [{ size: "75x135", price: 880000, number: 2 }],
        date: 2,
        sale: 14,
        off: 0.15,
        color: "#704214",
    },
    {
        id: 18,
        name: "حوله کلاسیک زرشکی",
        source: "/images/BestSallers/classic-red.jpg",
        type: "حوله تنپوش مردانه",
        details: [
            { size: "S", price: 2300000, number: 0 },
            { size: "M", price: 2600000, number: 1 },
            { size: "L", price: 2890000, number: 1 },
            { size: "XL", price: 3150000, number: 1 },
            { size: "XXL", price: 33800000, number: 1 },
        ],
        date: 2,
        sale: 14,
        off: 0,
        color: "#4A0404",
    },

    {
        id: 19,
        name: "حوله دستی پلنگی",
        source: "/images/BestSallers/dastiPalangi-neskafeh.jpg",
        type: "حوله دستی",
        details: [{ size: "30x60", price: 190000, number: 33 }],
        date: 1,
        sale: 14,
        off: 0,
        color: "#967259",
    },
    {
        id: 20,
        name: "حوله کفشدوزک",
        source: "/images/BestSallers/kafhduzak-red.jpg",
        type: "حوله استخری",
        details: [
            { size: "S", price: 2300000, number: 1 },
            { size: "M", price: 2600000, number: 1 },
            { size: "L", price: 2890000, number: 1 },
            { size: "XL", price: 3150000, number: 0 },
            { size: "XXL", price: 33800000, number: 0 },
        ],
        date: 2,
        sale: 14,
        off: 0.15,
        color: "#780606",
    },
    {
        id: 21,
        name: "حوله پلنگی خاکی",
        source: "/images/BestSallers/palangi-khaki.jpg",
        type: "حوله تنپوش زنانه",
        details: [
            { size: "S", price: 2300000, number: 1 },
            { size: "M", price: 2600000, number: 1 },
            { size: "L", price: 2890000, number: 1 },
            { size: "XL", price: 3150000, number: 1 },
            { size: "XXL", price: 33800000, number: 1 },
        ],
        date: 2,
        sale: 14,
        off: 0,
        color: "#EAE0C8",
    },
    {
        id: 22,
        name: "خرگوش صورتی",
        source: "/images/BestSallers/rabit-pink.jpg",
        type: "حوله تنپوش کودک",
        details: [
            { size: "60", price: 1150000, number: 1 },
            { size: "70", price: 1300000, number: 1 },
            { size: "80", price: 1500000, number: 1 },
            { size: "90", price: 1600000, number: 0 },
            { size: "100", price: 1880000, number: 0 },
        ],
        date: 2,
        sale: 14,
        off: 0.1,
        color: "#F06292",
    },
    {
        id: 23,
        name: "حوله مکوئین قرمز",
        source: "/images/BestSallers/mac-red.jpg",
        type: "حوله تنپوش کودک",
        details: [
            { size: "60", price: 1150000, number: 1 },
            { size: "70", price: 1300000, number: 1 },
            { size: "80", price: 1500000, number: 1 },
            { size: "90", price: 1600000, number: 1 },
            { size: "100", price: 1880000, number: 1 },
        ],
        date: 2,
        sale: 14,
        off: 0,
        color: "#780606",
    },
    {
        id: 24,
        name: "حوله دستی لویی ویتون ",
        source: "/images/Card-img/viton-nescafe-dasti.jpg",
        type: "حوله دستی",
        details: [{ size: "40x80", price: 280000, number: 12 }],
        date: 2,
        sale: 14,
        off: 0,
        color: "#704214",
    },
    {
        id: 25,
        name: "حوله دیبا زرشکی",
        source: "/images/Card-img/dibaZereshki.jpg",
        type: "حوله تنپوش مردانه",
        details: [
            { size: "S", price: 2300000, number: 1 },
            { size: "M", price: 2600000, number: 1 },
            { size: "L", price: 2890000, number: 1 },
            { size: "XL", price: 3150000, number: 0 },
            { size: "XXL", price: 33800000, number: 0 },
        ],
        date: 1,
        sale: 1,
        off: 0.5,
        color: "#4A0404",
    },
    {
        id: 26,
        name: "حوله دستی کیتی ",
        source: "/images/Card-img/kiti-60.jpg",
        type: "حوله دستی",
        details: [{ size: "30x60", price: 200000, number: 12 }],
        date: 2,
        sale: 34,
        off: 0,
        color: "#F06292",
    },
    {
        id: 27,
        name: "حوله ملوان سرمه ای ",
        source: "/images/Card-img/malavansormeii.jpg",
        type: "حوله تنپوش مردانه",
        details: [
            { size: "S", price: 2300000, number: 0 },
            { size: "M", price: 2600000, number: 1 },
            { size: "L", price: 2890000, number: 1 },
            { size: "XL", price: 3150000, number: 1 },
            { size: "XXL", price: 33800000, number: 0 },
        ],
        date: 2,
        sale: 9,
        off: 0.1,
        color: "#111184",
    },
    {
        id: 28,
        name: "حوله ملوان طوسی ",
        source: "/images/Card-img/malavanTosi.jpg",
        type: "حوله تنپوش مردانه",
        details: [
            { size: "S", price: 2300000, number: 0 },
            { size: "M", price: 2600000, number: 1 },
            { size: "L", price: 2890000, number: 1 },
            { size: "XL", price: 3150000, number: 1 },
            { size: "XXL", price: 33800000, number: 1 },
        ],
        date: 2,
        sale: 14,
        off: 0,
        color: "#90A4AE",
    },
    {
        id: 29,
        name: "حوله پیکاسو آبی ",
        source: "/images/Card-img/paradaisAbi.jpg",
        type: "حوله تنپوش مردانه",
        details: [
            { size: "S", price: 2300000, number: 1 },
            { size: "M", price: 2600000, number: 1 },
            { size: "L", price: 2890000, number: 1 },
            { size: "XL", price: 3150000, number: 1 },
            { size: "XXL", price: 33800000, number: 0 },
        ],
        date: 2,
        sale: 14,
        off: 0,
        color: "#1976D2",
    },
    {
        id: 30,
        name: "حوله استخری رئال مادرید ",
        source: "/images/Card-img/reAl-70.jpg",
        type: "حوله استخری",
        details: [{ size: "75x135", price: 880000, number: 12 }],
        date: 2,
        sale: 8,
        off: 0.8,
        color: "#ffffffff",
    },
    {
        id: 31,
        name: "حوله تابان زرد ",
        source: "/images/Card-img/tabanZard.jpg",
        type: "حوله تنپوش زنانه",
        details: [
            { size: "S", price: 2300000, number: 1 },
            { size: "M", price: 2600000, number: 1 },
            { size: "L", price: 2890000, number: 1 },
            { size: "XL", price: 3150000, number: 0 },
            { size: "XXL", price: 33800000, number: 0 },
        ],
        date: 1,
        sale: 14,
        off: 0,
        color: "#FFD54F",
    },
];
export default productsNew;
