const productsNew = [
    {
        id: 1,
        name: "حوله لبوبو صورتی",
        source: "/images/Card-img/labubu-pink.jpg",
        type: "kids",
        details: [
            { size: "60", price: 1150000, number: 0 },
            { size: "70", price: 1300000, number: 0 },
            { size: "80", price: 1500000, number: 1 },
            { size: "90", price: 1600000, number: 1 },
            { size: "100", price: 1880000, number: 1 },
        ],
        date: 1,
        sale: 4,
        off: 0,
    },
    {
        id: 2,
        name: "حوله لبوبو بنفش",
        source: "/images/Card-img/labubu-perple.jpg",
        type: "kids",
        details: [
            { size: "60", price: 1150000, number: 0 },
            { size: "70", price: 1300000, number: 1 },
            { size: "80", price: 1500000, number: 1 },
            { size: "90", price: 1600000, number: 0 },
            { size: "100", price: 1880000, number: 1 },
        ],
        date: 1,
        sale: 4,
        off: 0,
    },
    {
        id: 3,
        name: "حوله باب اسفنجی",
        source: "/images/Card-img/bob-abi.jpg",
        type: "kids",
        details: [
            { size: "60", price: 1150000, number: 1 },
            { size: "70", price: 1300000, number: 1 },
            { size: "80", price: 1500000, number: 1 },
            { size: "90", price: 1600000, number: 1 },
            { size: "100", price: 1880000, number: 1 },
        ],
        date: 1,
        sale: 4,
        off: 0,
    },
    {
        id: 4,
        name: "حوله ورساچه سفید ",
        source: "/images/Card-img/versach-sefid.jpg",
        type: "adult",
        details: [
            { size: "S", price: 2300000, number: 0 },
            { size: "M", price: 2600000, number: 1 },
            { size: "L", price: 2890000, number: 1 },
            { size: "XL", price: 3150000, number: 1 },
            { size: "XXL", price: 33800000, number: 0 },
        ],
        date: 1,
        sale: 4,
        off: 0,
    },
    {
        id: 5,
        name: "حوله ورساچه مشکی",
        source: "/images/Card-img/versach-meshki.jpg",
        type: "adult",
        details: [
            { size: "S", price: 2300000, number: 1 },
            { size: "M", price: 2600000, number: 1 },
            { size: "L", price: 2890000, number: 1 },
            { size: "XL", price: 3150000, number: 1 },
            { size: "XXL", price: 33800000, number: 0 },
        ],
        date: 1,
        sale: 4,
        off: 0,
    },

    {
        id: 6,
        name: "حوله دستی پونی",
        source: "/images/Card-img/pony-30.jpg",
        type: "hand",
        details: [{ size: "30x30", price: 110000, number: 33 }],
        date: 1,
        sale: 4,
        off: 0,
    },
    {
        id: 7,
        name: "حوله استخری مردعنکبوتی",
        source: "/images/Card-img/spiderman-gym.jpg",
        type: "gym",
        details: [{ size: "75x135", price: 880000, number: 2 }],
        date: 1,
        sale: 4,
        off: 0,
    },
    {
        id: 8,
        name: "حوله لیلیوم صورتی",
        source: "/images/Card-img/lilium-sorati.jpg",
        type: "adult",
        details: [
            { size: "S", price: 2300000, number: 1 },
            { size: "M", price: 2600000, number: 1 },
            { size: "L", price: 2890000, number: 1 },
            { size: "XL", price: 3150000, number: 0 },
            { size: "XXL", price: 33800000, number: 0 },
        ],
        date: 1,
        sale: 4,
        off: 0,
    },
    {
        id: 9,
        name: "حوله لیلیوم شیری",
        source: "/images/Card-img/lilium-shiri.jpg",
        type: "adult-woman",
        details: [
            { size: "S", price: 2300000, number: 1 },
            { size: "M", price: 2600000, number: 1 },
            { size: "L", price: 2890000, number: 1 },
            { size: "XL", price: 3150000, number: 0 },
            { size: "XXL", price: 33800000, number: 0 },
        ],
        date: 1,
        sale: 4,
        off: 0,
    },
    {
        id: 10,
        name: "حوله کیتی",
        source: "/images/Card-img/kiti-sorati.jpg",
        type: "kids",
        details: [
            { size: "60", price: 1150000, number: 1 },
            { size: "70", price: 1300000, number: 1 },
            { size: "80", price: 1500000, number: 1 },
            { size: "90", price: 1600000, number: 1 },
            { size: "100", price: 1880000, number: 1 },
        ],
        date: 1,
        sale: 4,
        off: 0,
    },
    {
        id: 11,
        name: "حوله کرومی صورتی",
        source: "/images/Card-img/kuromi-sorati.jpg",
        type: "kids",
        details: [
            { size: "60", price: 1150000, number: 0 },
            { size: "70", price: 1300000, number: 1 },
            { size: "80", price: 1500000, number: 1 },
            { size: "90", price: 1600000, number: 1 },
            { size: "100", price: 1880000, number: 1 },
        ],
        date: 1,
        sale: 4,
        off: 0,
    },
    {
        id: 12,
        name: "حوله کرومی بنفش",
        source: "/images/Card-img/kuromi-banafsh.jpg",
        type: "kids",
        details: [
            { size: "60", price: 1150000, number: 0 },
            { size: "70", price: 1300000, number: 1 },
            { size: "80", price: 1500000, number: 1 },
            { size: "90", price: 1600000, number: 1 },
            { size: "100", price: 1880000, number: 1 },
        ],
        date: 1,
        sale: 4,
        off: 0,
    },
    {
        id: 13,
        name: "حوله حمامی لویی ویتون",
        source: "/images/Card-img/viton-toosi-bath.jpg",
        type: "bath",
        details: [{ size: "90x150", price: 1250000, number: 5 }],
        date: 2,
        sale: 14,
        off: 0,
    },

    {
        id: 14,
        name: "حوله پارادایس صورتی",
        source: "/images/BestSallers/paradais-pink.jpg",
        type: "adult-woman",
        details: [
            { size: "S", price: 2300000, number: 1 },
            { size: "M", price: 2600000, number: 1 },
            { size: "L", price: 2890000, number: 1 },
            { size: "XL", price: 3150000, number: 0 },
            { size: "XXL", price: 33800000, number: 0 },
        ],
        date: 2,
        sale: 14,
        off: 0.1,
    },
    {
        id: 15,
        name: "حوله پانچو پونی",
        source: "/images/BestSallers/pony-panchi.jpg",
        type: "gym",
        details: [{ size: "70", price: 1300000, number: 1 }],
        date: 2,
        sale: 14,
        off: 0,
    },
    {
        id: 16,
        name: "حوله سورن لیمویی",
        source: "/images/BestSallers/soren-limo.jpg",
        type: "adult-woman",
        details: [
            { size: "S", price: 2300000, number: 0 },
            { size: "M", price: 2600000, number: 1 },
            { size: "L", price: 2890000, number: 1 },
            { size: "XL", price: 3150000, number: 1 },
            { size: "XXL", price: 33800000, number: 0 },
        ],
        date: 2,
        sale: 14,
        off: 0,
    },
    {
        id: 17,
        name: "حوله آفتاب قهوه ای",
        source: "/images/BestSallers/aftab-kerem.jpg",
        type: "gym",
        details: [{ size: "75x135", price: 880000, number: 2 }],
        date: 2,
        sale: 14,
        off: 0.15,
    },
    {
        id: 18,
        name: "حوله کلاسیک زرشکی",
        source: "/images/BestSallers/classic-red.jpg",
        type: "adult-men",
        details: [
            { size: "S", price: 2300000, number: 0 },
            { size: "M", price: 2600000, number: 1 },
            { size: "L", price: 2890000, number: 1 },
            { size: "XL", price: 3150000, number: 1 },
            { size: "XXL", price: 33800000, number: 1 },
        ],
        date: 2,
        sale: 14,
        off: 0,
    },

    {
        id: 19,
        name: "حوله دستی پلنگی",
        source: "/images/BestSallers/dastiPalangi-neskafeh.jpg",
        type: "hand",
        details: [{ size: "30x60", price: 190000, number: 33 }],
        date: 1,
        sale: 14,
        off: 0,
    },
    {
        id: 20,
        name: "حوله کفشدوزک",
        source: "/images/BestSallers/kafhduzak-red.jpg",
        type: "gym",
        details: [
            { size: "S", price: 2300000, number: 1 },
            { size: "M", price: 2600000, number: 1 },
            { size: "L", price: 2890000, number: 1 },
            { size: "XL", price: 3150000, number: 0 },
            { size: "XXL", price: 33800000, number: 0 },
        ],
        date: 2,
        sale: 14,
        off: 0.15,
    },
    {
        id: 21,
        name: "حوله پلنگی خاکی",
        source: "/images/BestSallers/palangi-khaki.jpg",
        type: "adult-woman",
        details: [
            { size: "S", price: 2300000, number: 1 },
            { size: "M", price: 2600000, number: 1 },
            { size: "L", price: 2890000, number: 1 },
            { size: "XL", price: 3150000, number: 1 },
            { size: "XXL", price: 33800000, number: 1 },
        ],
        date: 2,
        sale: 14,
        off: 0,
    },
    {
        id: 22,
        name: "خرگوش صورتی",
        source: "/images/BestSallers/rabit-pink.jpg",
        type: "kids",
        details: [
            { size: "60", price: 1150000, number: 1 },
            { size: "70", price: 1300000, number: 1 },
            { size: "80", price: 1500000, number: 1 },
            { size: "90", price: 1600000, number: 0 },
            { size: "100", price: 1880000, number: 0 },
        ],
        date: 2,
        sale: 14,
        off: 0.1,
    },
    {
        id: 23,
        name: "حوله مکوئین قرمز",
        source: "/images/BestSallers/mac-red.jpg",
        type: "kids",
        details: [
            { size: "60", price: 1150000, number: 1 },
            { size: "70", price: 1300000, number: 1 },
            { size: "80", price: 1500000, number: 1 },
            { size: "90", price: 1600000, number: 1 },
            { size: "100", price: 1880000, number: 1 },
        ],
        date: 2,
        sale: 14,
        off: 0,
    },
    {
        id: 24,
        name: "حوله دستی لویی ویتون ",
        source: "/images/Card-img/viton-nescafe-dasti.jpg",
        type: "hand",
        details: [{ size: "40x80", price: 280000, number: 12 }],
        date: 2,
        sale: 14,
        off: 0,
    },
];
export default productsNew;
