const productsBestSaller = [
    {
        id: 1,
        name: "حوله پارادایس صورتی",
        source: "./images/BestSallers/paradais-pink.jpg",
        type: "adult",
        details: [
            { size: "S", price: 2300000, number: 1 },
            { size: "M", price: 2600000, number: 1 },
            { size: "L", price: 2890000, number: 1 },
            { size: "XL", price: 3150000, number: 0 },
            { size: "XXL", price: 33800000, number: 0 },
        ],
        off: 0.1,
    },
    {
        id: 2,
        name: "حوله پانچو پونی",
        source: "./images/BestSallers/pony-panchi.jpg",
        type: "gym",
        details: [{ size: "70", price: 1300000, number: 1 }],
        off: 0,
    },
    {
        id: 3,
        name: "حوله سورن لیمویی",
        source: "./images/BestSallers/soren-limo.jpg",
        type: "adult",
        details: [
            { size: "S", price: 2300000, number: 0 },
            { size: "M", price: 2600000, number: 1 },
            { size: "L", price: 2890000, number: 1 },
            { size: "XL", price: 3150000, number: 1 },
            { size: "XXL", price: 33800000, number: 0 },
        ],
        off: 0,
    },
    {
        id: 4,
        name: "حوله آفتاب قهوه ای",
        source: "./images/BestSallers/aftab-kerem.jpg",
        type: "gym",
        details: [{ size: "75x135", price: 880000, number: 2 }],
        off: 0.15,
    },
    {
        id: 5,
        name: "حوله کلاسیک زرشکی",
        source: "./images/BestSallers/classic-red.jpg",
        type: "adult",
        details: [
            { size: "S", price: 2300000, number: 0 },
            { size: "M", price: 2600000, number: 1 },
            { size: "L", price: 2890000, number: 1 },
            { size: "XL", price: 3150000, number: 1 },
            { size: "XXL", price: 33800000, number: 1 },
        ],
        off: 0,
    },

    {
        id: 6,
        name: "حوله دستی پلنگی",
        source: "./images/BestSallers/dastiPalangi-neskafeh.jpg",
        type: "hand",
        details: [{ size: "30x60", price: 190000, number: 33 }],
        off: 0,
    },
    {
        id: 7,
        name: "حوله کفشدوزک",
        source: "./images/BestSallers/kafhduzak-red.jpg",
        type: "gym",
        details: [
            { size: "S", price: 2300000, number: 1 },
            { size: "M", price: 2600000, number: 1 },
            { size: "L", price: 2890000, number: 1 },
            { size: "XL", price: 3150000, number: 0 },
            { size: "XXL", price: 33800000, number: 0 },
        ],
        off: 0.15,
    },
    {
        id: 8,
        name: "حوله پلنگی خاکی",
        source: "./images/BestSallers/palangi-khaki.jpg",
        type: "adult",
        details: [
            { size: "S", price: 2300000, number: 1 },
            { size: "M", price: 2600000, number: 1 },
            { size: "L", price: 2890000, number: 1 },
            { size: "XL", price: 3150000, number: 1 },
            { size: "XXL", price: 33800000, number: 1 },
        ],
        off: 0,
    },
    {
        id: 9,
        name: "خرگوش صورتی",
        source: "./images/BestSallers/rabit-pink.jpg",
        type: "kids",
        details: [
            { size: "60", price: 1150000, number: 1 },
            { size: "70", price: 1300000, number: 1 },
            { size: "80", price: 1500000, number: 1 },
            { size: "90", price: 1600000, number: 0 },
            { size: "100", price: 1880000, number: 0 },
        ],
        off: 0.1,
    },
    {
        id: 10,
        name: "حوله مکوئین قرمز",
        source: "./images/BestSallers/mac-red.jpg",
        type: "kids",
        details: [
            { size: "60", price: 1150000, number: 1 },
            { size: "70", price: 1300000, number: 1 },
            { size: "80", price: 1500000, number: 1 },
            { size: "90", price: 1600000, number: 1 },
            { size: "100", price: 1880000, number: 1 },
        ],
        off: 0,
    },
];
export default productsBestSaller;
